CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "role" varchar NOT NULL,
  "created_at" datetime
);

CREATE TABLE "courses" (
  "course_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text,
  "instructor_id" int NOT NULL,
  "category" varchar,
  "level" varchar,
  "created_at" datetime
);

CREATE TABLE "lessons" (
  "lesson_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int NOT NULL,
  "title" varchar,
  "content" text,
  "lesson_order" int,
  "duration_minutes" int
);

CREATE TABLE "enrollments" (
  "enrollment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" int NOT NULL,
  "course_id" int NOT NULL,
  "enrolled_at" datetime,
  "status" varchar
);

CREATE TABLE "assignments" (
  "assignment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int NOT NULL,
  "title" varchar,
  "description" text,
  "due_date" datetime
);

CREATE TABLE "submissions" (
  "submission_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assignment_id" int NOT NULL,
  "student_id" int NOT NULL,
  "submitted_at" datetime,
  "grade" decimal
);

CREATE TABLE "progress" (
  "progress_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" int NOT NULL,
  "lesson_id" int NOT NULL,
  "completed" boolean,
  "completed_at" datetime
);

COMMENT ON COLUMN "users"."role" IS 'student | instructor | admin';

COMMENT ON COLUMN "courses"."level" IS 'beginner | intermediate | advanced';

COMMENT ON COLUMN "enrollments"."status" IS 'active | completed | dropped';

ALTER TABLE "courses" ADD FOREIGN KEY ("instructor_id") REFERENCES "users" ("user_id");

ALTER TABLE "lessons" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("course_id");

ALTER TABLE "enrollments" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("user_id");

ALTER TABLE "enrollments" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("course_id");

ALTER TABLE "assignments" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("course_id");

ALTER TABLE "submissions" ADD FOREIGN KEY ("assignment_id") REFERENCES "assignments" ("assignment_id");

ALTER TABLE "submissions" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("user_id");

ALTER TABLE "progress" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("user_id");

ALTER TABLE "progress" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("lesson_id");
